services:
   db:
     image: mysql:8.0.33
     environment:
       MYSQL_ROOT_PASSWORD: or1-1
       MYSQL_DATABASE: announcements
       LANG: en_US.UTF-8
     ports:
       - "3306:3306"
     volumes:
       - ./dbDesign/database.sql:/docker-entrypoint-initdb.d/init.sql
     restart: unless-stopped

   backend:
     build: ./Backend
     ports:
       - "8080:8080"
     depends_on:
       - db
     environment:
       MYSQL_HOST: db
       MYSQL_PORT: 3306
       MYSQL_USER: root
       MYSQL_PASSWORD: or1-1
     restart: always

   frontend:
     image: front
     build:
       context: ./FrontEnd
       dockerfile: frontDocker
     ports:
       - "80:80"
     volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
